spring.application.name=DockerUsageTest
server.port=8090
app.message=${APP_MESSAGE:Hello from default container!}

AWS_CREDENTIALS_ACCESSKEY=suDjE6YRYBsnsnggbuP7w5
AWS_CREDENTIALS_SECRETKEY=6tLo3LMu81W2C6i81Z18UMZSF9qaVUngTQGu6TcnBYbr
CVISION_TOKEN=gtXivBB1VExguyKHfCtT9FbdCBvZq5i2LdnXWb3GNC9vynYDT
